return table.list_to_set({
	"AR United Forces",
	"Assault Tweaks Standalone Lite",
	"Assault Tweaks Standalone",
	"Better Cops weapon usage (multiplayer edition)",
	"Better Cops weapon usage and some tweaks (multiplayer edition)",
	"Better Cops weapon usage and some tweaks",
	"Better Cops weapon usage",
	"Classic Heisting Reborn",
	"Corrected Faction Spawns",
	"Crackdown",
	"Death Wish +",
	"Eclipse",
	"Enemy Accuracy Fix",
	"Full Speed Swarm",
	"Ire and Fist",
	"Less Cops",
	"LIES",
	"Mayhem And Deathwish Assualt Tweaks",
	"Mildly Alarming Enemy Spawngroups",
	"Original Enemy AI",
	"Payday 2 Hyper Heisting Shin Shootout",
	"RestorationMod",
	"Reworked Enemy AI",
	"Snap's Spawngroups",
	"Somewhat un-spawncampable groups",
	"Tmod base 200301",
	"United Offensive Plus",
	"United Offensive",
	"Update Special Enemies More Often"
})